source "https://rubygems.org"

gem "jekyll", "~> 4.3"

gem "jekyll-seo-tag", ">= 2.0"
gem "rake", ">= 12.3.1"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"

# docs-only
gem "jekyll-github-metadata", ">= 2.15"